spring.data.mongodb.database=testing
spring.data.mongodb.uri=${MONGODB_URI}
jwt.secret=${JWT_SECRET}
app.security.username=${APP_USERNAME}
app.security.password=${APP_PASSWORD}
#spring.data.mongodb.uri=mongodb+srv://tyler15215237:15215237@cluster0.bwaxyee.mongodb.net/
#jwt.secret=a-very-long-32-bits-secret-key-here!
#app.security.username=user
#app.security.password=password
spring.cache.type=redis
spring.redis.host=coppery-daughter-umbra-24016.db.redis.io
spring.redis.port=17078
spring.redis.username=default
spring.redis.password=fvXtNVTxsrGAcCnc1WAOs1I35NduRh8G
