spring.data.mongodb.database=testing
#spring.data.mongodb.uri=${MONGODB_URI}
#jwt.secret=${JWT_SECRET}
#app.security.username=${APP_USERNAME}
#app.security.password=${APP_PASSWORD}
spring.data.mongodb.uri=mongodb+srv://tyler15215237:15215237@cluster0.bwaxyee.mongodb.net/
jwt.secret=a-very-long-32-bits-secret-key-here!
app.security.username=user
app.security.password=password

#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379
spring.cache.type={SPRING_CACHE_TYPE}
spring.redis.host={SPRING_REDIS_HOST}
spring.redis.port={SPRING_REDIS_PORT}
spring.redis.username={SPRING_REDIS_USERNAME}
spring.redis.password={SPRING_REDIS_PASSWORD}
