spring.data.mongodb.database=testing
//spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.uri=${MONGODB_URI}
jwt.secret=${JWT_SECRET}
app.security.username=${APP_USERNAME}
app.security.password=${APP_PASSWORD}
